# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: StapleCode
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ironpilot
github_username:  ironpilot

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# OSS SS
theme: oss-soft-serve
permalink: /docs/:title

# main colors:
colors:
  primary: firebrick
  secondary: salmon
# Basic product information.
name: StapleCode
# If you have nothing to say, you should, but we'll skip to installation
description: "
If your already familiar with other PHP MVC frameworks then setup will be a breeze. If you're literally just getting started with MVC frameworks, no worries! Our documentation site can answer many questions and provides a wealth of examples."
logo: "/assets/staplecode-logo.svg"        #/images/path/to/logo

# Version and license
version: 1.0  # http://semver.org/
license: GNU # https://opensource.org/licenses/MIT

# Where is your product available?
# If you need a source not listed, add below. OSS Soft-Serve will loop.
main_repo:
  name: Github
  url: https://github.com/ironpilot/Staple-Code
  fork: true # assumes Github if true; adds upper corner badge
  color: red # fork badge color: Red Orange Yellow Olive Green Teal Blue Violet Purple Pink Brown Grey Black

# Any secondary distribution sources?
repos:
  gem:
  nuget:

# Product CTAs (Calls to Action).
cta:
  main: "An open source php framework"
  secondary:
